// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRpTGE3p2ndhE-KurwPTEvix7OS19C6fI',
    appId: '1:932022239005:web:a33ef8597742c86a4d6bf4',
    messagingSenderId: '932022239005',
    projectId: 'yummy-chat-6d604',
    authDomain: 'yummy-chat-6d604.firebaseapp.com',
    storageBucket: 'yummy-chat-6d604.appspot.com',
    measurementId: 'G-C8SBT105SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA19vo1jWhvfWm473Uk6EaZg735LkVw58Y',
    appId: '1:932022239005:android:3431fa4701cfb7624d6bf4',
    messagingSenderId: '932022239005',
    projectId: 'yummy-chat-6d604',
    storageBucket: 'yummy-chat-6d604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgRU3jUx6pFWHE_1txoZRGa-cPpEOAh6w',
    appId: '1:932022239005:ios:7a85a2751d777c3b4d6bf4',
    messagingSenderId: '932022239005',
    projectId: 'yummy-chat-6d604',
    storageBucket: 'yummy-chat-6d604.appspot.com',
    iosClientId: '932022239005-0jbj3ekj6cdmro1hk6qkp1c56k54fpr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.yummyChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgRU3jUx6pFWHE_1txoZRGa-cPpEOAh6w',
    appId: '1:932022239005:ios:00a13986c9a9fe2f4d6bf4',
    messagingSenderId: '932022239005',
    projectId: 'yummy-chat-6d604',
    storageBucket: 'yummy-chat-6d604.appspot.com',
    iosClientId: '932022239005-ms6j9cde9mhj7epnpakn78kg9rncsp5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.yummyChat.RunnerTests',
  );
}
